apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: test-app1-ingress
spec:
  entryPoints:
    - web 
  routes:
    - kind: Rule
      match: Host(`test-app1.metallb.pert.com.ar`) 
      services:
        - name: test-app1-service 
          port: 80
